package:
  name: diffpy.mpdf
  ## Use __conda_version__.txt.
  version: "1.0.0"

source:
  git_url: ..

build:
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy >=1.9.2
    - matplotlib
    - scipy
    - diffpy.structure
    - diffpy.srreal

test:
  # Python imports
  imports:
    - diffpy
    - diffpy.mpdf
    - diffpy.mpdf.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - diffpy.structure
    - diffpy.srreal

about:
  home: https://github.com/benfrandsen/mPDFmodules/
  summary: Tools for calculating the magnetic pair distribution function.
  license: Modified BSD License
  license_file: LICENSE.txt

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.
